/**
 * Type-safe ClickHouse client.
 *
 * Wraps @clickhouse/client with schema-aware methods that use
 * the generated Database types for compile-time validation.
 *
 * @example
 * ```ts
 * import { createClient } from '@chtype/client';
 * import type { Database } from './generated/schema';
 *
 * const ch = createClient<Database>({
 *   url: 'http://localhost:8123',
 *   database: 'my_db',
 * });
 *
 * // Type-safe query — result type inferred from the builder
 * const rows = await ch.execute(
 *   qb.selectFrom('users').select(['user_id', 'name']).compile()
 * );
 * // rows is typed as Pick<UsersRow, 'user_id' | 'name'>[]
 *
 * // Type-safe insert — validated against UsersInsert
 * await ch.insert('users', [{ user_id: '123', name: 'Alice' }]);
 * ```
 */

import {
  type ClickHouseClient as BaseClient,
  type ClickHouseClientConfigOptions,
  createClient as createBaseClient,
} from '@clickhouse/client';
import type {
  CompiledQuery,
  DatabaseSchema,
  InsertType,
  TableName,
} from '@chtype/query';

export interface ChtypeClientOptions extends ClickHouseClientConfigOptions {}

export interface ChtypeClient<DB extends DatabaseSchema> {
  /** Execute a compiled SELECT query and return typed rows. */
  execute<TResult>(query: CompiledQuery<TResult>): Promise<TResult[]>;

  /** Execute a raw SQL query with optional parameters. */
  query<T = Record<string, unknown>>(
    sql: string,
    params?: Record<string, unknown>,
  ): Promise<T[]>;

  /** Insert rows into a table. Type-checked against the table's Insert type. */
  insert<T extends TableName<DB>>(
    table: T,
    rows: InsertType<DB, T>[],
  ): Promise<void>;

  /** Execute a DDL/ALTER command (raw SQL, no parameterization). */
  command(sql: string): Promise<void>;

  /** Close the client connection. */
  close(): Promise<void>;

  /** Access the underlying @clickhouse/client instance. */
  readonly raw: BaseClient;
}

/**
 * Create a type-safe ClickHouse client.
 *
 * The generic parameter `DB` should be the `Database` interface
 * generated by `@chtype/codegen`.
 */
export function createClient<DB extends DatabaseSchema>(
  options: ChtypeClientOptions,
): ChtypeClient<DB> {
  const client = createBaseClient(options);

  return {
    async execute<TResult>(query: CompiledQuery<TResult>): Promise<TResult[]> {
      const result = await client.query({
        query: query.sql,
        query_params: query.params,
        format: 'JSONEachRow',
      });
      return result.json<TResult>();
    },

    async query<T = Record<string, unknown>>(
      sql: string,
      params?: Record<string, unknown>,
    ): Promise<T[]> {
      const result = await client.query({
        query: sql,
        query_params: params,
        format: 'JSONEachRow',
      });
      return result.json<T>();
    },

    async insert<T extends TableName<DB>>(
      table: T,
      rows: InsertType<DB, T>[],
    ): Promise<void> {
      if (rows.length === 0) return;
      await client.insert({
        table: table as string,
        values: rows,
        format: 'JSONEachRow',
      });
    },

    async command(sql: string): Promise<void> {
      await client.command({ query: sql });
    },

    async close(): Promise<void> {
      await client.close();
    },

    get raw(): BaseClient {
      return client;
    },
  };
}
