/**
 * TypeScript code generator.
 *
 * Takes introspected table metadata and generates:
 * - Per-table Row interfaces (for SELECT results)
 * - Per-table Insert interfaces (DEFAULT fields optional, MATERIALIZED/ALIAS excluded)
 * - A Database registry type mapping table names to their types + engine metadata
 */

import type { IntrospectedColumn, IntrospectedTable } from './introspect.js';
import { type TypeMapperOptions, mapClickHouseType } from './type-mapper.js';

export interface GeneratorOptions extends TypeMapperOptions {
  /** Database name (for the header comment) */
  database: string;
  /** CLI command used to generate (for the header comment) */
  command?: string;
}

/** Convert snake_case to PascalCase */
function snakeToPascal(s: string): string {
  return s
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

/** Generate the Row interface name for a table */
function rowName(tableName: string): string {
  return `${snakeToPascal(tableName)}Row`;
}

/** Generate the Insert interface name for a table */
function insertName(tableName: string): string {
  return `${snakeToPascal(tableName)}Insert`;
}

/** Generate a JSDoc comment block */
function jsdoc(lines: string[]): string {
  if (lines.length === 0) return '';
  if (lines.length === 1) return `/** ${lines[0]} */\n`;
  return `/**\n${lines.map((l) => ` * ${l}`).join('\n')}\n */\n`;
}

/** Generate the Row interface for a table */
function generateRowInterface(table: IntrospectedTable, options: GeneratorOptions): string {
  const docLines = [
    `Table: \`${table.name}\``,
    `Engine: ${table.engineFull || table.engine}`,
  ];
  if (table.sortingKey) docLines.push(`ORDER BY: (${table.sortingKey})`);
  if (table.partitionKey) docLines.push(`PARTITION BY: ${table.partitionKey}`);
  if (table.versionColumn) docLines.push(`Version column: ${table.versionColumn}`);
  if (table.comment) docLines.push('', table.comment);

  const fields = table.columns.map((col) => {
    const tsType = mapClickHouseType(col.type, options);
    const comment = col.comment ? `  /** ${col.comment} */\n` : '';
    return `${comment}  ${col.name}: ${tsType};`;
  });

  return `${jsdoc(docLines)}export interface ${rowName(table.name)} {\n${fields.join('\n')}\n}`;
}

/** Generate the Insert interface for a table */
function generateInsertInterface(table: IntrospectedTable, options: GeneratorOptions): string {
  // Filter out MATERIALIZED and ALIAS columns — they can't be inserted
  const insertableColumns = table.columns.filter(
    (col) => col.defaultKind !== 'MATERIALIZED' && col.defaultKind !== 'ALIAS',
  );

  if (insertableColumns.length === 0) return '';

  const fields = insertableColumns.map((col) => {
    const tsType = mapClickHouseType(col.type, options);
    // Columns with DEFAULT are optional on insert
    const optional = col.defaultKind === 'DEFAULT' ? '?' : '';
    const comment = col.comment ? `  /** ${col.comment} */\n` : '';
    return `${comment}  ${col.name}${optional}: ${tsType};`;
  });

  return `/** Insert type for \`${table.name}\` — DEFAULT columns are optional, MATERIALIZED/ALIAS columns excluded. */\nexport interface ${insertName(table.name)} {\n${fields.join('\n')}\n}`;
}

/** Generate the Database registry type */
function generateDatabaseType(tables: IntrospectedTable[]): string {
  const entries = tables.map((table) => {
    const engineLiteral = JSON.stringify(table.engine);
    const versionLiteral = table.versionColumn
      ? JSON.stringify(table.versionColumn)
      : 'null';

    return `  ${table.name}: {\n    row: ${rowName(table.name)};\n    insert: ${insertName(table.name)};\n    engine: ${engineLiteral};\n    versionColumn: ${versionLiteral};\n  };`;
  });

  return `/** Database registry — maps table names to their Row/Insert types and engine metadata. */\nexport interface Database {\n${entries.join('\n')}\n}`;
}

/**
 * Generate a complete TypeScript source file from introspected tables.
 */
export function generate(tables: IntrospectedTable[], options: GeneratorOptions): string {
  const header = [
    '// @generated by @chtype/codegen',
    `// Database: ${options.database}`,
    `// Generated at: ${new Date().toISOString()}`,
    options.command ? `// Command: ${options.command}` : '',
    '//',
    '// Do not edit manually — regenerate with: npx @chtype/codegen generate',
    '',
  ]
    .filter(Boolean)
    .join('\n');

  const sections: string[] = [header];

  for (const table of tables) {
    sections.push(generateRowInterface(table, options));
    const insertIface = generateInsertInterface(table, options);
    if (insertIface) sections.push(insertIface);
  }

  sections.push(generateDatabaseType(tables));

  // Final newline
  return `${sections.join('\n\n')}\n`;
}
