/**
 * TypeScript code generator.
 *
 * Takes introspected table metadata and generates:
 * - Per-table Row interfaces (for SELECT results)
 * - Per-table Insert interfaces (DEFAULT fields optional, MATERIALIZED/ALIAS excluded)
 * - A Database registry type mapping table names to their types + engine metadata
 */

import type { IntrospectedColumn, IntrospectedTable } from './introspect.js';
import { type TypeMapperOptions, mapClickHouseType } from './type-mapper.js';

export interface GeneratorOptions extends TypeMapperOptions {
  database: string;
  command?: string;
}

/** Valid JS identifier pattern — names that don't match need quoting. */
const VALID_IDENTIFIER = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

/** Quote a property name if it's not a valid JS identifier. */
function quoteProperty(name: string): string {
  return VALID_IDENTIFIER.test(name) ? name : `"${name}"`;
}

/** Convert snake_case to PascalCase, preserving casing within segments. */
function snakeToPascal(s: string): string {
  return s
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

function rowName(tableName: string): string {
  return `${snakeToPascal(tableName)}Row`;
}

function insertName(tableName: string): string {
  return `${snakeToPascal(tableName)}Insert`;
}

function jsdoc(lines: string[]): string {
  if (lines.length === 0) return '';
  if (lines.length === 1) return `/** ${lines[0]} */\n`;
  return `/**\n${lines.map((l) => ` * ${l}`).join('\n')}\n */\n`;
}

function generateRowInterface(table: IntrospectedTable, options: GeneratorOptions): string {
  const docLines = [
    `Table: \`${table.name}\``,
    `Engine: ${table.engineFull || table.engine}`,
  ];
  if (table.sortingKey) docLines.push(`ORDER BY: (${table.sortingKey})`);
  if (table.partitionKey) docLines.push(`PARTITION BY: ${table.partitionKey}`);
  if (table.versionColumn) docLines.push(`Version column: ${table.versionColumn}`);
  if (table.comment) docLines.push('', table.comment);

  const fields = table.columns.map((col) => {
    const tsType = mapClickHouseType(col.type, options);
    const comment = col.comment ? `  /** ${col.comment} */\n` : '';
    return `${comment}  ${quoteProperty(col.name)}: ${tsType};`;
  });

  return `${jsdoc(docLines)}export type ${rowName(table.name)} = {\n${fields.join('\n')}\n}`;
}

function generateInsertInterface(table: IntrospectedTable, options: GeneratorOptions): string {
  const insertableColumns = table.columns.filter(
    (col) => col.defaultKind !== 'MATERIALIZED' && col.defaultKind !== 'ALIAS',
  );

  if (insertableColumns.length === 0) return '';

  const insertOptions = { ...options, insertCoerce: true };
  const fields = insertableColumns.map((col) => {
    const tsType = mapClickHouseType(col.type, insertOptions);
    const optional = col.defaultKind === 'DEFAULT' ? '?' : '';
    const comment = col.comment ? `  /** ${col.comment} */\n` : '';
    return `${comment}  ${quoteProperty(col.name)}${optional}: ${tsType};`;
  });

  return `/** Insert type for \`${table.name}\` — DEFAULT columns are optional, MATERIALIZED/ALIAS columns excluded. */\nexport type ${insertName(table.name)} = {\n${fields.join('\n')}\n}`;
}

function generateDatabaseType(tables: IntrospectedTable[]): string {
  const entries = tables.map((table) => {
    const engineLiteral = JSON.stringify(table.engine);
    const versionLiteral = table.versionColumn ? JSON.stringify(table.versionColumn) : 'null';

    return `  ${quoteProperty(table.name)}: {\n    row: ${rowName(table.name)};\n    insert: ${insertName(table.name)};\n    engine: ${engineLiteral};\n    versionColumn: ${versionLiteral};\n  };`;
  });

  return `/** Database registry — maps table names to their Row/Insert types and engine metadata. */\nexport type Database = {\n${entries.join('\n')}\n}`;
}

export function generate(tables: IntrospectedTable[], options: GeneratorOptions): string {
  const header = [
    '// @generated by chtype',
    `// Database: ${options.database}`,
    `// Generated at: ${new Date().toISOString()}`,
    '//',
    '// Do not edit manually — regenerate with: npx chtype generate',
    '',
  ].join('\n');

  const sections: string[] = [header];

  for (const table of tables) {
    sections.push(generateRowInterface(table, options));
    const insertIface = generateInsertInterface(table, options);
    if (insertIface) sections.push(insertIface);
  }

  sections.push(generateDatabaseType(tables));

  return `${sections.join('\n\n')}\n`;
}
