import { describe, expect, it } from 'vitest';
import type { IntrospectedTable } from '../introspect.js';
import { generate } from '../generator.js';

const sampleTable: IntrospectedTable = {
  name: 'users',
  engine: 'ReplacingMergeTree',
  engineFull: 'ReplacingMergeTree(updated_at)',
  versionColumn: 'updated_at',
  sortingKey: 'user_id',
  partitionKey: '',
  primaryKey: 'user_id',
  comment: '',
  columns: [
    {
      name: 'user_id',
      type: 'String',
      defaultKind: '',
      defaultExpression: '',
      comment: 'Primary identifier',
      isInSortingKey: true,
      isInPrimaryKey: true,
      isInPartitionKey: false,
    },
    {
      name: 'name',
      type: 'String',
      defaultKind: '',
      defaultExpression: '',
      comment: '',
      isInSortingKey: false,
      isInPrimaryKey: false,
      isInPartitionKey: false,
    },
    {
      name: 'score',
      type: 'Nullable(Float64)',
      defaultKind: '',
      defaultExpression: '',
      comment: '',
      isInSortingKey: false,
      isInPrimaryKey: false,
      isInPartitionKey: false,
    },
    {
      name: 'tags',
      type: 'Array(String)',
      defaultKind: 'DEFAULT',
      defaultExpression: '[]',
      comment: '',
      isInSortingKey: false,
      isInPrimaryKey: false,
      isInPartitionKey: false,
    },
    {
      name: 'updated_at',
      type: 'DateTime64(3)',
      defaultKind: 'DEFAULT',
      defaultExpression: 'now64(3)',
      comment: '',
      isInSortingKey: false,
      isInPrimaryKey: false,
      isInPartitionKey: false,
    },
    {
      name: 'computed_field',
      type: 'String',
      defaultKind: 'MATERIALIZED',
      defaultExpression: "concat(user_id, '-', name)",
      comment: '',
      isInSortingKey: false,
      isInPrimaryKey: false,
      isInPartitionKey: false,
    },
  ],
};

describe('generate', () => {
  it('generates Row and Insert interfaces', () => {
    const output = generate([sampleTable], { database: 'test_db' });

    // Row interface should have all columns
    expect(output).toContain('export interface UsersRow {');
    expect(output).toContain('user_id: string;');
    expect(output).toContain('name: string;');
    expect(output).toContain('score: number | null;');
    expect(output).toContain('tags: string[];');
    expect(output).toContain('updated_at: string;');
    expect(output).toContain('computed_field: string;');
  });

  it('makes DEFAULT columns optional in Insert interface', () => {
    const output = generate([sampleTable], { database: 'test_db' });

    expect(output).toContain('export interface UsersInsert {');
    // DEFAULT columns should be optional
    expect(output).toContain('tags?: string[];');
    expect(output).toContain('updated_at?: string;');
    // Non-default columns should be required
    expect(output).toMatch(/\s+user_id: string;/);
    expect(output).toMatch(/\s+name: string;/);
  });

  it('excludes MATERIALIZED columns from Insert interface', () => {
    const output = generate([sampleTable], { database: 'test_db' });

    // The Insert interface should NOT contain computed_field
    const insertSection = output.split('export interface UsersInsert')[1]!.split('}')[0]!;
    expect(insertSection).not.toContain('computed_field');
  });

  it('generates Database registry type', () => {
    const output = generate([sampleTable], { database: 'test_db' });

    expect(output).toContain('export interface Database {');
    expect(output).toContain('users: {');
    expect(output).toContain('row: UsersRow;');
    expect(output).toContain('insert: UsersInsert;');
    expect(output).toContain('engine: "ReplacingMergeTree"');
    expect(output).toContain('versionColumn: "updated_at"');
  });

  it('includes JSDoc with engine metadata', () => {
    const output = generate([sampleTable], { database: 'test_db' });

    expect(output).toContain('Table: `users`');
    expect(output).toContain('Engine: ReplacingMergeTree(updated_at)');
    expect(output).toContain('ORDER BY: (user_id)');
    expect(output).toContain('Version column: updated_at');
  });

  it('includes header with generation metadata', () => {
    const output = generate([sampleTable], { database: 'test_db' });

    expect(output).toContain('// @generated by @chtype/codegen');
    expect(output).toContain('// Database: test_db');
    expect(output).toContain('// Do not edit manually');
  });

  it('includes column comments as JSDoc', () => {
    const output = generate([sampleTable], { database: 'test_db' });

    expect(output).toContain('/** Primary identifier */');
  });

  it('respects bigints option', () => {
    const tableWithBigInt: IntrospectedTable = {
      ...sampleTable,
      name: 'counters',
      columns: [
        {
          name: 'count',
          type: 'UInt64',
          defaultKind: '',
          defaultExpression: '',
          comment: '',
          isInSortingKey: false,
          isInPrimaryKey: false,
          isInPartitionKey: false,
        },
      ],
    };

    const withoutBigints = generate([tableWithBigInt], { database: 'test_db' });
    expect(withoutBigints).toContain('count: string;');

    const withBigints = generate([tableWithBigInt], { database: 'test_db', bigints: true });
    expect(withBigints).toContain('count: bigint;');
  });
});
