/**
 * Main query builder entry point.
 *
 * Creates type-safe SELECT and INSERT builders from a generated Database schema.
 *
 * @example
 * ```ts
 * import { createQueryBuilder } from '@chtype/query';
 * import type { Database } from './generated/schema';
 *
 * const qb = createQueryBuilder<Database>();
 *
 * const query = qb
 *   .selectFrom('users')
 *   .select(['user_id', 'name'])
 *   .where('user_id', '=', qb.param('id', 'String'))
 *   .compile();
 *
 * console.log(query.sql);
 * // SELECT user_id, name
 * // FROM users
 * // WHERE user_id = {id:String}
 * ```
 */

import type { DatabaseSchema, TableName } from './types.js';
import { type ClickHouseParamType, Param } from './param.js';
import { SelectBuilder } from './select-builder.js';
import { InsertBuilder } from './insert-builder.js';
import { fn } from './expressions.js';

export interface QueryBuilder<DB extends DatabaseSchema> {
  /** Start building a SELECT query on a table. */
  selectFrom<T extends TableName<DB>>(table: T): SelectBuilder<DB, T>;

  /** Start building an INSERT query on a table. */
  insertInto<T extends TableName<DB>>(table: T): InsertBuilder<DB, T>;

  /** Create a typed parameter placeholder. */
  param(name: string, type: ClickHouseParamType): Param;

  /** ClickHouse function helpers (argMax, count, sum, etc.) */
  fn: typeof fn;
}

/**
 * Create a type-safe query builder for your ClickHouse database.
 *
 * The generic parameter `DB` should be the `Database` interface
 * generated by `@chtype/codegen`.
 */
export function createQueryBuilder<DB extends DatabaseSchema>(): QueryBuilder<DB> {
  return {
    selectFrom<T extends TableName<DB>>(table: T): SelectBuilder<DB, T> {
      return new SelectBuilder<DB, T>(table);
    },

    insertInto<T extends TableName<DB>>(table: T): InsertBuilder<DB, T> {
      return new InsertBuilder<DB, T>(table);
    },

    param(name: string, type: ClickHouseParamType): Param {
      return new Param(name, type);
    },

    fn,
  };
}
