// @generated by @chtype/codegen
// Database: example_db
// Generated at: 2026-03-14T00:00:00.000Z
//
// Do not edit manually — regenerate with: npx @chtype/codegen generate

/**
 * Table: `users`
 * Engine: ReplacingMergeTree(updated_at)
 * ORDER BY: (user_id)
 */
export interface UsersRow {
  user_id: string;
  name: string;
  email: string;
  score: number | null;
  tags: string[];
  updated_at: string;
}

/** Insert type for `users` — DEFAULT columns are optional, MATERIALIZED/ALIAS columns excluded. */
export interface UsersInsert {
  user_id: string;
  name: string;
  email: string;
  score?: number | null;
  tags?: string[];
  updated_at?: string;
}

/**
 * Table: `events`
 * Engine: MergeTree
 * ORDER BY: (event_id)
 * PARTITION BY: toYYYYMM(timestamp)
 */
export interface EventsRow {
  event_id: string;
  user_id: string;
  type: string;
  payload: string;
  timestamp: string;
}

/** Insert type for `events` — DEFAULT columns are optional, MATERIALIZED/ALIAS columns excluded. */
export interface EventsInsert {
  event_id: string;
  user_id: string;
  type: string;
  payload: string;
  timestamp: string;
}

/** Database registry — maps table names to their Row/Insert types and engine metadata. */
export interface Database {
  users: {
    row: UsersRow;
    insert: UsersInsert;
    engine: "ReplacingMergeTree";
    versionColumn: "updated_at";
  };
  events: {
    row: EventsRow;
    insert: EventsInsert;
    engine: "MergeTree";
    versionColumn: null;
  };
}
